import { slugify } from "./slug";

export const DEFAULT_CATEGORY_NAMES = [
  "Boutique",
  "Restaurant",
  "Hôtel",
  "Pharmacie",
  "Cybercafé",
  "Garage",
  "Immobilier",
  "Agrobusiness",
  "Salon de coiffure",
  "Supermarché",
  "Électronique",
  "Téléphone & Accessoires",
  "Mode & Vêtements",
  "Chaussures",
  "Cosmétique & Beauté",
  "Quincaillerie",
  "Matériaux de construction",
  "Transport",
  "Taxi / Moto",
  "École",
  "Université",
  "Centre médical",
  "Clinique",
  "Laboratoire",
  "Banque / Microfinance",
  "Assurance",
  "Bureau de change",
  "Imprimerie",
  "Studio photo",
  "Événementiel",
  "Salle de fête",
  "Nettoyage",
  "Car Wash",
  "Station-service",
  "Restaurant rapide",
  "Boulangerie",
  "Pâtisserie",
  "Poissonnerie",
  "Boucherie",
  "Marché alimentaire",
  "Meubles",
  "Décoration",
  "Électroménager",
  "Services informatiques",
  "Réparation téléphone",
  "Réparation ordinateur",
  "Internet / WiFi",
  "Starlink / MikroTik",
  "ONG",
  "Église / Organisation",
  "Tourisme",
  "Hôtel appartement",
  "Location maison",
  "Location voiture",
  "Livraison",
  "Autres services",
] as const;

const CATEGORY_ICONS = [
  "🛍️", "🍽️", "🏨", "💊", "💻", "🔧", "🏢", "🌾", "💇", "🛒", "📺", "📱",
  "👗", "👟", "💄", "🧰", "🧱", "🚌", "🏍️", "🏫", "🎓", "🏥", "🩺", "🧪",
  "🏦", "🛡️", "💱", "🖨️", "📸", "🎉", "🎊", "🧼", "🚿", "⛽", "🍔", "🥖",
  "🧁", "🐟", "🥩", "🥬", "🪑", "🖼️", "🧺", "🧑‍💻", "📲", "🖥️", "📶", "🛰️",
  "🤝", "⛪", "🧳", "🏙️", "🏠", "🚗", "📦", "⭐",
] as const;

export const CATEGORY_ICON_BY_SLUG = Object.fromEntries(
  DEFAULT_CATEGORY_NAMES.map((name, index) => [slugify(name), CATEGORY_ICONS[index] ?? "📌"]),
);
